version: '3.4'

services:
  deliveryapi:
    image: ${DOCKER_REGISTRY-}deliveryapi
    build:
      context: .
      dockerfile: DeliveryAPI/Dockerfile
    depends_on:
      delivery_postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=delivery_postgres;Port=5432;Database=DelivrySerivceDb;Username=postgres;Password=089875
      - ASPNETCORE_URLS=https://+:443
    ports:
      - "56541:443"

  delivery_postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "089875"
      POSTGRES_DB: "DelivrySerivceDb"
    volumes:
      - beeline-storage:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  beeline-storage: {}